# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Nick Playfair
email: contact@nickplayfair.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Web developer from Nottingham, UK. Over the past few years I’ve been involved 
  in a number of projects doing frontend and backend development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.nickplayfair.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
timezone: Europe/London
google_analytics: "UA-65796796-1"
twitter_username: nplayfair
github_username:  nplayfair
instagram_username: nplayfair

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-gist
exclude:
  - Gemfile
  - Gemfile.lock
